#!/usr/bin/env python
# encoding: utf-8

from pelicanconf import *
SITEURL = SITEURL + '/fr'


#################
# Header
#################
HEADER_TITLE_FR = u'The Cali Garmo'
HEADER_SUBTITLE_FR = u'apprendre'

AUTHOR_FR = u'thecaligarmo'
SITENAME_FR = u'The Cali Garmo aprendre'
SITE_DESCRIPTION_FR = u'The Cali Garmo apprendre. Le math, les langues, tout.'
THEME = u'theme/thecaligarmo'

#################
# Navigation
#################
MENUITEMS_FR = (('Acceuil', SITEURL),)

#################
# Footer
#################
FOOTER_LEFT_COLUMN_TITLE_FR = u'The Cali Garmo'
FOOTER_LEFT_MENU_FR = (('Acceuil','http://thecaligarmo.com/'),)
FOOTER_MIDDLE_COLUMN_TITLE_FR = u'Social'
FOOTER_MIDDLE_MENU_FR = (('IG','http://instagram.com'),)
# FOOTER_RIGHT_COLUMN_TITLE_FR = u'Other'
# FOOTER_RIGHT_MENU_FR = ()
COPYRIGHT_FR = u'&copy; 2020'


#################
# Pagination
#################
#PAGINATION_PREVIOUS_FR = u''
#PAGINATION_NEXT_FR = u''

#################
# Page specific
#################
ARCHIVES_HEAD_TITLE_FR = u'Archives'
ARCHIVES_HEAD_DESCRIPTION_FR = u'Archives'
ARCHIVES_SUBHEADER_IMAGE_FR = False
ARCHIVES_SUBHEADER_TITLE_FR = u'Archives'
ARCHIVES_SUBHEADER_SUBTITLE_FR = u'Où l\'histoire vit'
ARCHIVES_CONTENT_TITLE_FR = u'Content'

ARTICLE_SUBHEADER_BY_FR = u'Par'
ARTICLE_SUBHEADER_PUBLISHED_FR = u'Publié'
ARTICLE_SUBHEADER_MODIFIED_FR = u'Modifié'
ARTICLE_SUBHEADER_IN_FR = u'Category:'
ARTICLE_RELATED_POSTS_TITLE_FR = u'Articles similaires'
COMMENT_TITLE_FR = u'Commentaires'

AUTHOR_HEAD_TITLE_FR = u'Auteur'
AUTHOR_HEAD_DESCRIPTION_FR = u'Auteur'
AUTHOR_SUBHEADER_SUBTITLE_FR = u'Auteur'
AUTHOR_CONTENT_TITLE_FR = u'Articles par '

AUTHORS_HEAD_TITLE_FR = u'Auteurs'
AUTHORS_HEAD_DESCRIPTION_FR = u'Auteurs'
AUTHORS_SUBHEADER_TITLE_FR = u'Aueters'
AUTHORS_SUBHEADER_SUBTITLE_FR = u''

CATEGORIES_HEAD_TITLE_FR = u'Catégories'
CATEGORIES_HEAD_DESCRIPTION_FR = u'Catégories'
CATEGORIES_SUBHEADER_TITLE_FR = u'Catégories'
CATEGORIES_SUBHEADER_SUBTITLE_FR = u''

CATEGORY_HEAD_TITLE_FR = u'Catégorie'
CATEGORY_SUBHEADER_TITLE_FR = u'Catégorie'
CATEGORY_SUBHEADER_SUBTITLE_FR = u''
CATEGORY_ARTICLES_TITLE_FR = u'Articles'
CATEGORY_SUBCATEGORIES_TITLE_FR = u'Souscatégories'

INDEX_HEAD_TITLE_FR = u'Acceuil'
INDEX_SUBHEADER_TITLE_FR = u'The Cali Garmo'
INDEX_SUBHEADER_SUBTITLE_FR = u''
INDEX_CONTENT_TITLE_FR = u'Articles'

PERIOD_ARCHIVES_HEAD_TITLE_FR = u'Period Archives'
PERIOD_ARCHIVES_HEAD_DESCRIPTION_FR = u'Period Archives'
PERIOD_ARCHIVES_SUBHEADER_TITLE_FR = u'Period Archives'
PERIOD_ARCHIVES_SUBHEADER_SUBTITLE_FR = u''
PERIOD_ARCHIVES_CONTENT_TITLE_FR = u'Content'

SEARCH_HEAD_TITLE_FR = u'Cherche'
SEARCH_SUBHEADER_TITLE_FR = u'Cherche'
SEARCH_SUBHEADER_SUBTITLE_FR = u''

TAG_HEAD_TITLE_FR = u'Tag'
TAG_HEAD_DESCRIPTION_FR = u'Tag'
TAG_SUBHEADER_TITLE_FR = u'Tag'
TAG_SUBHEADER_SUBTITLE_FR = u''
TAG_CONTENT_TITLE_FR = u'Articles tagged with'

TAGS_HEAD_TITLE_FR = u'Tags'
TAGS_HEAD_DESCRIPTION_FR = u'Tags'
TAGS_SUBHEADER_TITLE_FR = u'Tags'
TAGS_SUBHEADER_SUBTITLE_FR = u''
TAGS_CONTENT_TITLE_FR = u'Tag'
TAGS_CONTENT_LIST_FR = u''


SUBSITE_FR = {
    'HEADER_TITLE': HEADER_TITLE_FR,
    'HEADER_SUBTITLE': HEADER_SUBTITLE_FR,
    'AUTHOR': AUTHOR_FR,
    'SITENAME': SITENAME_FR,
    'SITE_DESCRIPTION': SITE_DESCRIPTION_FR,
    'THEME': THEME,
    'MENUITEMS': MENUITEMS_FR,
    'FOOTER_LEFT_COLUMN_TITLE': FOOTER_LEFT_COLUMN_TITLE_FR,
    'FOOTER_LEFT_MENU': FOOTER_LEFT_MENU_FR,
    'FOOTER_MIDDLE_COLUMN_TITLE': FOOTER_MIDDLE_COLUMN_TITLE_FR,
    'FOOTER_MIDDLE_MENU': FOOTER_MIDDLE_MENU_FR,
    #'FOOTER_RIGHT_COLUMN_TITLE': # FOOTER_RIGHT_COLUMN_TITLE_FR,
    #'FOOTER_RIGHT_MENU': # FOOTER_RIGHT_MENU_FR,
    'COPYRIGHT': COPYRIGHT_FR,
    #'PAGINATION_PREVIOUS': PAGINATION_PREVIOUS_FR,
    #'PAGINATION_NEXT': PAGINATION_NEXT_FR,
    'ARCHIVES_HEAD_TITLE': ARCHIVES_HEAD_TITLE_FR,
    'ARCHIVES_HEAD_DESCRIPTION': ARCHIVES_HEAD_DESCRIPTION_FR,
    'ARCHIVES_SUBHEADER_IMAGE': ARCHIVES_SUBHEADER_IMAGE_FR,
    'ARCHIVES_SUBHEADER_TITLE': ARCHIVES_SUBHEADER_TITLE_FR,
    'ARCHIVES_SUBHEADER_SUBTITLE': ARCHIVES_SUBHEADER_SUBTITLE_FR,
    'ARCHIVES_CONTENT_TITLE': ARCHIVES_CONTENT_TITLE_FR,
    'ARTICLE_SUBHEADER_BY': ARTICLE_SUBHEADER_BY_FR,
    'ARTICLE_SUBHEADER_PUBLISHED': ARTICLE_SUBHEADER_PUBLISHED_FR,
    'ARTICLE_SUBHEADER_MODIFIED': ARTICLE_SUBHEADER_MODIFIED_FR,
    'ARTICLE_SUBHEADER_IN': ARTICLE_SUBHEADER_IN_FR,
    'ARTICLE_RELATED_POSTS_TITLE': ARTICLE_RELATED_POSTS_TITLE_FR,
    'COMMENT_TITLE': COMMENT_TITLE_FR,
    'AUTHOR_HEAD_TITLE': AUTHOR_HEAD_TITLE_FR,
    'AUTHOR_HEAD_DESCRIPTION': AUTHOR_HEAD_DESCRIPTION_FR,
    'AUTHOR_SUBHEADER_SUBTITLE': AUTHOR_SUBHEADER_SUBTITLE_FR,
    'AUTHOR_CONTENT_TITLE': AUTHOR_CONTENT_TITLE_FR,
    'AUTHORS_HEAD_TITLE': AUTHORS_HEAD_TITLE_FR,
    'AUTHORS_HEAD_DESCRIPTION': AUTHORS_HEAD_DESCRIPTION_FR,
    'AUTHORS_SUBHEADER_TITLE': AUTHORS_SUBHEADER_TITLE_FR,
    'AUTHORS_SUBHEADER_SUBTITLE': AUTHORS_SUBHEADER_SUBTITLE_FR,
    'CATEGORIES_HEAD_TITLE': CATEGORIES_HEAD_TITLE_FR,
    'CATEGORIES_HEAD_DESCRIPTION': CATEGORIES_HEAD_DESCRIPTION_FR,
    'CATEGORIES_SUBHEADER_TITLE': CATEGORIES_SUBHEADER_TITLE_FR,
    'CATEGORIES_SUBHEADER_SUBTITLE': CATEGORIES_SUBHEADER_SUBTITLE_FR,
    'CATEGORY_HEAD_TITLE': CATEGORY_HEAD_TITLE_FR,
    'CATEGORY_SUBHEADER_TITLE': CATEGORY_SUBHEADER_TITLE_FR,
    'CATEGORY_SUBHEADER_SUBTITLE': CATEGORY_SUBHEADER_SUBTITLE_FR,
    'CATEGORY_ARTICLES_TITLE': CATEGORY_ARTICLES_TITLE_FR,
    'CATEGORY_SUBCATEGORIES_TITLE': CATEGORY_SUBCATEGORIES_TITLE_FR,
    'INDEX_HEAD_TITLE': INDEX_HEAD_TITLE_FR,
    'INDEX_SUBHEADER_TITLE': INDEX_SUBHEADER_TITLE_FR,
    'INDEX_SUBHEADER_SUBTITLE': INDEX_SUBHEADER_SUBTITLE_FR,
    'INDEX_CONTENT_TITLE': INDEX_CONTENT_TITLE_FR,
    'PERIOD_ARCHIVES_HEAD_TITLE': PERIOD_ARCHIVES_HEAD_TITLE_FR,
    'PERIOD_ARCHIVES_HEAD_DESCRIPTION': PERIOD_ARCHIVES_HEAD_DESCRIPTION_FR,
    'PERIOD_ARCHIVES_SUBHEADER_TITLE': PERIOD_ARCHIVES_SUBHEADER_TITLE_FR,
    'PERIOD_ARCHIVES_SUBHEADER_SUBTITLE': PERIOD_ARCHIVES_SUBHEADER_SUBTITLE_FR,
    'PERIOD_ARCHIVES_CONTENT_TITLE': PERIOD_ARCHIVES_CONTENT_TITLE_FR,
    'SEARCH_HEAD_TITLE': SEARCH_HEAD_TITLE_FR,
    'SEARCH_SUBHEADER_TITLE': SEARCH_SUBHEADER_TITLE_FR,
    'SEARCH_SUBHEADER_SUBTITLE': SEARCH_SUBHEADER_SUBTITLE_FR,
    'TAG_HEAD_TITLE': TAG_HEAD_TITLE_FR,
    'TAG_HEAD_DESCRIPTION': TAG_HEAD_DESCRIPTION_FR,
    'TAG_SUBHEADER_TITLE': TAG_SUBHEADER_TITLE_FR,
    'TAG_SUBHEADER_SUBTITLE': TAG_SUBHEADER_SUBTITLE_FR,
    'TAG_CONTENT_TITLE': TAG_CONTENT_TITLE_FR,
    'TAGS_HEAD_TITLE': TAGS_HEAD_TITLE_FR,
    'TAGS_HEAD_DESCRIPTION': TAGS_HEAD_DESCRIPTION_FR,
    'TAGS_SUBHEADER_TITLE': TAGS_SUBHEADER_TITLE_FR,
    'TAGS_SUBHEADER_SUBTITLE': TAGS_SUBHEADER_SUBTITLE_FR,
    'TAGS_CONTENT_TITLE': TAGS_CONTENT_TITLE_FR,
    'TAGS_CONTENT_LIST': TAGS_CONTENT_LIST_FR,
}


