#!/usr/bin/env python

from pelicanconf import *
SITEURL = SITEURL + '/fr'

AUTHOR_FR = u'thecaligarmo'
SITENAME_FR = u'The Cali Garmo is Learning'
SITE_DESCRIPTION_FR = u'The Cali Garmo is Learning. Be it Maths, Languages, or Life Lessons.'

#################
# Header
#################
HEADER_TITLE_FR = 'Le Cali Garmo'
HEADER_SUBTITLE_FR = 'en train d\'apprendre'


#################
# Navigation
#################
MENUITEMS_FR = (('Home', SITEURL+"/fr"),)

#################
# Footer
#################
FOOTER_LEFT_COLUMN_TITLE_FR = 'The Cali Garmo'
FOOTER_LEFT_MENU_FR = (('Home','http://thecaligarmo.com/'),)
FOOTER_MIDDLE_COLUMN_TITLE_FR = 'Social'
FOOTER_MIDDLE_MENU_FR = (('IG','ig.com'),)
# FOOTER_RIGHT_COLUMN_TITLE_FR = 'Other'
# FOOTER_RIGHT_MENU_FR = ()
COPYRIGHT_FR = '&copy; 2020'


#################
# Pagination
#################
#PAGINATION_PREVIOUS_FR = ''
#PAGINATION_NEXT_FR = ''

#################
# Page specific
#################
ARCHIVES_HEAD_TITLE_FR = 'Archives'
ARCHIVES_HEAD_DESCRIPTION_FR = 'Archives'
ARCHIVES_SUBHEADER_TITLE_FR = 'Archives'
ARCHIVES_SUBHEADER_SUBTITLE_FR = 'Where the past resides'
ARCHIVES_CONTENT_TITLE_FR = 'Content'

ARTICLE_SUBHEADER_BY_FR = 'By'
ARTICLE_SUBHEADER_PUBLISHED_FR = 'Published on'
ARTICLE_SUBHEADER_MODIFIED_FR = 'Last modified'
ARTICLE_SUBHEADER_IN_FR = 'Category:'
ARTICLE_RELATED_POSTS_TITLE_FR = 'Related Posts'
COMMENT_TITLE_FR = 'Comments'

AUTHOR_HEAD_TITLE_FR = 'Author'
AUTHOR_HEAD_DESCRIPTION_FR = 'Author'
AUTHOR_SUBHEADER_SUBTITLE_FR = 'Author'
AUTHOR_CONTENT_TITLE_FR = 'Articles by '

AUTHORS_HEAD_TITLE_FR = 'Authors'
AUTHORS_HEAD_DESCRIPTION_FR = 'Authors'
AUTHORS_SUBHEADER_TITLE_FR = 'Authors'
AUTHORS_SUBHEADER_SUBTITLE_FR = ''

CATEGORIES_HEAD_TITLE_FR = 'Categories'
CATEGORIES_HEAD_DESCRIPTION_FR = 'Categories'
CATEGORIES_SUBHEADER_TITLE_FR = 'Categories'
CATEGORIES_SUBHEADER_SUBTITLE_FR = ''

CATEGORY_HEAD_TITLE_FR = 'Category'
CATEGORY_SUBHEADER_TITLE_FR = 'Category'
CATEGORY_SUBHEADER_SUBTITLE_FR = ''

INDEX_HEAD_TITLE_FR = 'Home'
INDEX_SUBHEADER_TITLE_FR = 'The Cali Garmo'
INDEX_SUBHEADER_SUBTITLE_FR = ''
INDEX_CONTENT_TITLE_FR = 'Articles'

PERIOD_ARCHIVES_HEAD_TITLE_FR = 'Period Archives'
PERIOD_ARCHIVES_HEAD_DESCRIPTION_FR = 'Period Archives'
PERIOD_ARCHIVES_SUBHEADER_TITLE_FR = 'Period Archives'
PERIOD_ARCHIVES_SUBHEADER_SUBTITLE_FR = ''
PERIOD_ARCHIVES_CONTENT_TITLE_FR = 'Content'

SEARCH_HEAD_TITLE_FR = 'Search'
SEARCH_SUBHEADER_TITLE_FR = 'Search'
SEARCH_SUBHEADER_SUBTITLE_FR = ''

TAG_HEAD_TITLE_FR = 'Tag'
TAG_HEAD_DESCRIPTION_FR = 'Tag'
TAG_SUBHEADER_TITLE_FR = 'Tag'
TAG_SUBHEADER_SUBTITLE_FR = ''
TAG_CONTENT_TITLE_FR = 'Articles tagged with'

TAGS_HEAD_TITLE_FR = 'Tags'
TAGS_HEAD_DESCRIPTION_FR = 'Tags'
TAGS_SUBHEADER_TITLE_FR = 'Tags'
TAGS_SUBHEADER_SUBTITLE_FR = ''
TAGS_CONTENT_TITLE_FR = 'Tag'
TAGS_CONTENT_LIST_FR = ''



SUBSITE_FR = {
        'THEME': 'theme/thecaligarmo',
        'AUTHOR_FR':AUTHOR_FR,
        'SITENAME_FR':SITENAME_FR,
        'SITE_DESCRIPTION_FR':SITE_DESCRIPTION_FR,
        'HEADER_TITLE_FR':HEADER_TITLE_FR,
        'HEADER_SUBTITLE_FR':HEADER_SUBTITLE_FR,
        'MENUITEMS_FR':MENUITEMS_FR,
        'FOOTER_LEFT_COLUMN_TITLE_FR':FOOTER_LEFT_COLUMN_TITLE_FR,
        'FOOTER_LEFT_MENU_FR':FOOTER_LEFT_MENU_FR,
        'FOOTER_MIDDLE_COLUMN_TITLE_FR':FOOTER_MIDDLE_COLUMN_TITLE_FR,
        'FOOTER_MIDDLE_MENU_FR':FOOTER_MIDDLE_MENU_FR,
#        'FOOTER_RIGHT_COLUMN_TITLE_FR':FOOTER_RIGHT_COLUMN_TITLE_FR,
#        'FOOTER_RIGHT_MENU_FR':FOOTER_RIGHT_MENU_FR,
        'COPYRIGHT_FR':COPYRIGHT_FR,
#        'PAGINATION_PREVIOUS_FR':PAGINATION_PREVIOUS_FR,
#        'PAGINATION_NEXT_FR':PAGINATION_NEXT_FR,
        'ARCHIVES_HEAD_TITLE_FR':ARCHIVES_HEAD_TITLE_FR,
        'ARCHIVES_HEAD_DESCRIPTION_FR':ARCHIVES_HEAD_DESCRIPTION_FR,
        'ARCHIVES_SUBHEADER_TITLE_FR':ARCHIVES_SUBHEADER_TITLE_FR,
        'ARCHIVES_SUBHEADER_SUBTITLE_FR':ARCHIVES_SUBHEADER_SUBTITLE_FR,
        'ARCHIVES_CONTENT_TITLE_FR':ARCHIVES_CONTENT_TITLE_FR,
        'ARTICLE_SUBHEADER_BY_FR':ARTICLE_SUBHEADER_BY_FR,
        'ARTICLE_SUBHEADER_PUBLISHED_FR':ARTICLE_SUBHEADER_PUBLISHED_FR,
        'ARTICLE_SUBHEADER_MODIFIED_FR':ARTICLE_SUBHEADER_MODIFIED_FR,
        'ARTICLE_SUBHEADER_IN_FR':ARTICLE_SUBHEADER_IN_FR,
        'ARTICLE_RELATED_POSTS_TITLE_FR':ARTICLE_RELATED_POSTS_TITLE_FR,
        'COMMENT_TITLE_FR':COMMENT_TITLE_FR,
        'AUTHOR_HEAD_TITLE_FR':AUTHOR_HEAD_TITLE_FR,
        'AUTHOR_HEAD_DESCRIPTION_FR':AUTHOR_HEAD_DESCRIPTION_FR,
        'AUTHOR_SUBHEADER_SUBTITLE_FR':AUTHOR_SUBHEADER_SUBTITLE_FR,
        'AUTHOR_CONTENT_TITLE_FR':AUTHOR_CONTENT_TITLE_FR,
        'AUTHORS_HEAD_TITLE_FR':AUTHORS_HEAD_TITLE_FR,
        'AUTHORS_HEAD_DESCRIPTION_FR':AUTHORS_HEAD_DESCRIPTION_FR,
        'AUTHORS_SUBHEADER_TITLE_FR':AUTHORS_SUBHEADER_TITLE_FR,
        'AUTHORS_SUBHEADER_SUBTITLE_FR':AUTHORS_SUBHEADER_SUBTITLE_FR,
        'CATEGORIES_HEAD_TITLE_FR':CATEGORIES_HEAD_TITLE_FR,
        'CATEGORIES_HEAD_DESCRIPTION_FR':CATEGORIES_HEAD_DESCRIPTION_FR,
        'CATEGORIES_SUBHEADER_TITLE_FR':CATEGORIES_SUBHEADER_TITLE_FR,
        'CATEGORIES_SUBHEADER_SUBTITLE_FR':CATEGORIES_SUBHEADER_SUBTITLE_FR,
        'CATEGORY_HEAD_TITLE_FR':CATEGORY_HEAD_TITLE_FR,
        'CATEGORY_SUBHEADER_TITLE_FR':CATEGORY_SUBHEADER_TITLE_FR,
        'CATEGORY_SUBHEADER_SUBTITLE_FR':CATEGORY_SUBHEADER_SUBTITLE_FR,
        'INDEX_HEAD_TITLE_FR':INDEX_HEAD_TITLE_FR,
        'INDEX_SUBHEADER_TITLE_FR':INDEX_SUBHEADER_TITLE_FR,
        'INDEX_SUBHEADER_SUBTITLE_FR':INDEX_SUBHEADER_SUBTITLE_FR,
        'INDEX_CONTENT_TITLE_FR':INDEX_CONTENT_TITLE_FR,
        'PERIOD_ARCHIVES_HEAD_TITLE_FR':PERIOD_ARCHIVES_HEAD_TITLE_FR,
        'PERIOD_ARCHIVES_HEAD_DESCRIPTION_FR':PERIOD_ARCHIVES_HEAD_DESCRIPTION_FR,
        'PERIOD_ARCHIVES_SUBHEADER_TITLE_FR':PERIOD_ARCHIVES_SUBHEADER_TITLE_FR,
        'PERIOD_ARCHIVES_SUBHEADER_SUBTITLE_FR':PERIOD_ARCHIVES_SUBHEADER_SUBTITLE_FR,
        'PERIOD_ARCHIVES_CONTENT_TITLE_FR':PERIOD_ARCHIVES_CONTENT_TITLE_FR,
        'SEARCH_HEAD_TITLE_FR':SEARCH_HEAD_TITLE_FR,
        'SEARCH_SUBHEADER_TITLE_FR':SEARCH_SUBHEADER_TITLE_FR,
        'SEARCH_SUBHEADER_SUBTITLE_FR':SEARCH_SUBHEADER_SUBTITLE_FR,
        'TAG_HEAD_TITLE_FR':TAG_HEAD_TITLE_FR,
        'TAG_HEAD_DESCRIPTION_FR':TAG_HEAD_DESCRIPTION_FR,
        'TAG_SUBHEADER_TITLE_FR':TAG_SUBHEADER_TITLE_FR,
        'TAG_SUBHEADER_SUBTITLE_FR':TAG_SUBHEADER_SUBTITLE_FR,
        'TAG_CONTENT_TITLE_FR':TAG_CONTENT_TITLE_FR,
        'TAGS_HEAD_TITLE_FR':TAGS_HEAD_TITLE_FR,
        'TAGS_HEAD_DESCRIPTION_FR':TAGS_HEAD_DESCRIPTION_FR,
        'TAGS_SUBHEADER_TITLE_FR':TAGS_SUBHEADER_TITLE_FR,
        'TAGS_SUBHEADER_SUBTITLE_FR':TAGS_SUBHEADER_SUBTITLE_FR,
        'TAGS_CONTENT_TITLE_FR':TAGS_CONTENT_TITLE_FR,
        'TAGS_CONTENT_LIST_FR':TAGS_CONTENT_LIST_FR,
    }
